server:
  port: 8443

spring:
  main:
    allow-bean-definition-overriding: true

  application:
    name: employee_mgmt_ms
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5432/companydb
    username: admin_user
    password: 12345
    driver-class-name: org.postgresql.Driver
    platform: postgres
    initialization-mode: never

  liquibase:
    enabled: true
    default-schema: employee
    change-log: classpath:db/changelog/db.changelog-master.xml

  security:
    user:
      name: ""      # leave empty if you use your own user store
      password: ""  # leave empty if you use your own user store



  kafka:
    #bootstrap-servers: kafka:9092
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

akhq:
  connections:
    kafka:
      properties:
        bootstrap-servers: localhost:9092

logging:
  level:
    org:
      apache:
        kafka: DEBUG
      springframework:
        kafka: DEBUG

# src/main/resources/application.yml
jwt:
  secret: change_this_to_a_secure_secret
  expiration: 3600000