server:
  port: 8081

spring:
  main:
    allow-bean-definition-overriding: true

  application:
    name: employee_mgmt_ms
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:postgresql://localhost:5432/companydb
    username: admin_user
    password: 12345
    driver-class-name: org.postgresql.Driver
    platform: postgres
    initialization-mode: never

  liquibase:
    enabled: true
    default-schema: employee
    change-log: classpath:db/changelog/db.changelog-master.xml

  security:
    user:
      name: ""      # leave empty if you use your own user store
      password: ""  # leave empty if you use your own user store

  cloud:
    vault:
      uri: http://localhost:8200
      token: root
      kv:
        enabled: true
        backend: my-secret
        default-context: jwt


  kafka:
    #bootstrap-servers: kafka:9092
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

akhq:
  connections:
    kafka:
      properties:
        bootstrap-servers: localhost:9092

logging:
  level:
    org:
      apache:
        kafka: DEBUG
      springframework:
        kafka: DEBUG

# src/main/resources/application.yml
jwt:
  secret: 2bbff1a3d3bfd3ec7a293af3ac99e82bea2336c8d9a1072c427dfad943120a1ce352713f9f513355c7fcba4c660a79fea514c73fe251ff878c2f3a047a1a757e
  expiration: 3600000

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics
  endpoint:
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}